// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/issuerenaming/go/models"
	"github.com/fullstack-lang/issuerenaming/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __Bar__dummysDeclaration__ models.Bar
var __Bar_time__dummyDeclaration time.Duration

// An BarID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getBar updateBar deleteBar
type BarID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// BarInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postBar updateBar
type BarInput struct {
	// The Bar to submit or modify
	// in: body
	Bar *orm.BarAPI
}

// GetBars
//
// swagger:route GET /bars bars getBars
//
// # Get all bars
//
// Responses:
// default: genericError
//
//	200: barDBResponse
func GetBars(c *gin.Context) {
	db := orm.BackRepo.BackRepoBar.GetDB()

	// source slice
	var barDBs []orm.BarDB
	query := db.Find(&barDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	barAPIs := make([]orm.BarAPI, 0)

	// for each bar, update fields from the database nullable fields
	for idx := range barDBs {
		barDB := &barDBs[idx]
		_ = barDB
		var barAPI orm.BarAPI

		// insertion point for updating fields
		barAPI.ID = barDB.ID
		barDB.CopyBasicFieldsToBar(&barAPI.Bar)
		barAPI.BarPointersEnconding = barDB.BarPointersEnconding
		barAPIs = append(barAPIs, barAPI)
	}

	c.JSON(http.StatusOK, barAPIs)
}

// PostBar
//
// swagger:route POST /bars bars postBar
//
// Creates a bar
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostBar(c *gin.Context) {
	db := orm.BackRepo.BackRepoBar.GetDB()

	// Validate input
	var input orm.BarAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create bar
	barDB := orm.BarDB{}
	barDB.BarPointersEnconding = input.BarPointersEnconding
	barDB.CopyBasicFieldsFromBar(&input.Bar)

	query := db.Create(&barDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoBar.CheckoutPhaseOneInstance(&barDB)
	bar := (*orm.BackRepo.BackRepoBar.Map_BarDBID_BarPtr)[barDB.ID]

	if bar != nil {
		models.AfterCreateFromFront(&models.Stage, bar)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, barDB)
}

// GetBar
//
// swagger:route GET /bars/{ID} bars getBar
//
// Gets the details for a bar.
//
// Responses:
// default: genericError
//
//	200: barDBResponse
func GetBar(c *gin.Context) {
	db := orm.BackRepo.BackRepoBar.GetDB()

	// Get barDB in DB
	var barDB orm.BarDB
	if err := db.First(&barDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var barAPI orm.BarAPI
	barAPI.ID = barDB.ID
	barAPI.BarPointersEnconding = barDB.BarPointersEnconding
	barDB.CopyBasicFieldsToBar(&barAPI.Bar)

	c.JSON(http.StatusOK, barAPI)
}

// UpdateBar
//
// swagger:route PATCH /bars/{ID} bars updateBar
//
// # Update a bar
//
// Responses:
// default: genericError
//
//	200: barDBResponse
func UpdateBar(c *gin.Context) {
	db := orm.BackRepo.BackRepoBar.GetDB()

	// Get model if exist
	var barDB orm.BarDB

	// fetch the bar
	query := db.First(&barDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.BarAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	barDB.CopyBasicFieldsFromBar(&input.Bar)
	barDB.BarPointersEnconding = input.BarPointersEnconding

	query = db.Model(&barDB).Updates(barDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	barNew := new(models.Bar)
	barDB.CopyBasicFieldsToBar(barNew)

	// get stage instance from DB instance, and call callback function
	barOld := (*orm.BackRepo.BackRepoBar.Map_BarDBID_BarPtr)[barDB.ID]
	if barOld != nil {
		models.AfterUpdateFromFront(&models.Stage, barOld, barNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the barDB
	c.JSON(http.StatusOK, barDB)
}

// DeleteBar
//
// swagger:route DELETE /bars/{ID} bars deleteBar
//
// # Delete a bar
//
// default: genericError
//
//	200: barDBResponse
func DeleteBar(c *gin.Context) {
	db := orm.BackRepo.BackRepoBar.GetDB()

	// Get model if exist
	var barDB orm.BarDB
	if err := db.First(&barDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&barDB)

	// get an instance (not staged) from DB instance, and call callback function
	barDeleted := new(models.Bar)
	barDB.CopyBasicFieldsToBar(barDeleted)

	// get stage instance from DB instance, and call callback function
	barStaged := (*orm.BackRepo.BackRepoBar.Map_BarDBID_BarPtr)[barDB.ID]
	if barStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, barStaged, barDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
