// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { BarDB } from '../bar-db'
import { BarService } from '../bar.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-barstable',
  templateUrl: './bars-table.component.html',
  styleUrls: ['./bars-table.component.css'],
})
export class BarsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Bar instances
  selection: SelectionModel<BarDB> = new (SelectionModel)
  initialSelection = new Array<BarDB>()

  // the data source for the table
  bars: BarDB[] = []
  matTableDataSource: MatTableDataSource<BarDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.bars
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (barDB: BarDB, property: string) => {
      switch (property) {
        case 'ID':
          return barDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return barDB.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (barDB: BarDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the barDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += barDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private barService: BarService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of bar instances
    public dialogRef: MatDialogRef<BarsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.barService.BarServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getBars()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
      ]
      this.selection = new SelectionModel<BarDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getBars()
    this.matTableDataSource = new MatTableDataSource(this.bars)
  }

  getBars(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.bars = this.frontRepo.Bars_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let bar of this.bars) {
            let ID = this.dialogData.ID
            let revPointer = bar[this.dialogData.ReversePointer as keyof BarDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(bar)
            }
            this.selection = new SelectionModel<BarDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, BarDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as BarDB[]
          for (let associationInstance of sourceField) {
            let bar = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as BarDB
            this.initialSelection.push(bar)
          }

          this.selection = new SelectionModel<BarDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.bars
      }
    )
  }

  // newBar initiate a new bar
  // create a new Bar objet
  newBar() {
  }

  deleteBar(barID: number, bar: BarDB) {
    // list of bars is truncated of bar before the delete
    this.bars = this.bars.filter(h => h !== bar);

    this.barService.deleteBar(barID).subscribe(
      bar => {
        this.barService.BarServiceChanged.next("delete")
      }
    );
  }

  editBar(barID: number, bar: BarDB) {

  }

  // display bar in router
  displayBarInRouter(barID: number) {
    this.router.navigate(["github_com_fullstack_lang_issuerenaming_go-" + "bar-display", barID])
  }

  // set editor outlet
  setEditorRouterOutlet(barID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_issuerenaming_go_editor: ["github_com_fullstack_lang_issuerenaming_go-" + "bar-detail", barID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.bars.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.bars.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<BarDB>()

      // reset all initial selection of bar that belong to bar
      for (let bar of this.initialSelection) {
        let index = bar[this.dialogData.ReversePointer as keyof BarDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(bar)

      }

      // from selection, set bar that belong to bar
      for (let bar of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = bar[this.dialogData.ReversePointer as keyof BarDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(bar)
      }


      // update all bar (only update selection & initial selection)
      for (let bar of toUpdate) {
        this.barService.updateBar(bar)
          .subscribe(bar => {
            this.barService.BarServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, BarDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedBar = new Set<number>()
      for (let bar of this.initialSelection) {
        if (this.selection.selected.includes(bar)) {
          // console.log("bar " + bar.Name + " is still selected")
        } else {
          console.log("bar " + bar.Name + " has been unselected")
          unselectedBar.add(bar.ID)
          console.log("is unselected " + unselectedBar.has(bar.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let bar = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as BarDB
      if (unselectedBar.has(bar.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<BarDB>) = new Array<BarDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          bar => {
            if (!this.initialSelection.includes(bar)) {
              // console.log("bar " + bar.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + bar.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = bar.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = bar.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("bar " + bar.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<BarDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
