// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { FooDB } from '../foo-db'
import { FooService } from '../foo.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-foo-sorting',
  templateUrl: './foo-sorting.component.html',
  styleUrls: ['./foo-sorting.component.css']
})
export class FooSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Foo instances that are in the association
  associatedFoos = new Array<FooDB>();

  constructor(
    private fooService: FooService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of foo instances
    public dialogRef: MatDialogRef<FooSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getFoos()
  }

  getFoos(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let foo of this.frontRepo.Foos_array) {
          let ID = this.dialogData.ID
          let revPointerID = foo[this.dialogData.ReversePointer as keyof FooDB] as unknown as NullInt64
          let revPointerID_Index = foo[this.dialogData.ReversePointer + "_Index" as keyof FooDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedFoos.push(foo)
          }
        }

        // sort associated foo according to order
        this.associatedFoos.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedFoos, event.previousIndex, event.currentIndex);

    // set the order of Foo instances
    let index = 0

    for (let foo of this.associatedFoos) {
      let revPointerID_Index = foo[this.dialogData.ReversePointer + "_Index" as keyof FooDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedFoos.forEach(
      foo => {
        this.fooService.updateFoo(foo)
          .subscribe(foo => {
            this.fooService.FooServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
