// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { BarDB } from '../bar-db'
import { BarService } from '../bar.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-bar-sorting',
  templateUrl: './bar-sorting.component.html',
  styleUrls: ['./bar-sorting.component.css']
})
export class BarSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Bar instances that are in the association
  associatedBars = new Array<BarDB>();

  constructor(
    private barService: BarService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of bar instances
    public dialogRef: MatDialogRef<BarSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getBars()
  }

  getBars(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let bar of this.frontRepo.Bars_array) {
          let ID = this.dialogData.ID
          let revPointerID = bar[this.dialogData.ReversePointer as keyof BarDB] as unknown as NullInt64
          let revPointerID_Index = bar[this.dialogData.ReversePointer + "_Index" as keyof BarDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedBars.push(bar)
          }
        }

        // sort associated bar according to order
        this.associatedBars.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedBars, event.previousIndex, event.currentIndex);

    // set the order of Bar instances
    let index = 0

    for (let bar of this.associatedBars) {
      let revPointerID_Index = bar[this.dialogData.ReversePointer + "_Index" as keyof BarDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedBars.forEach(
      bar => {
        this.barService.updateBar(bar)
          .subscribe(bar => {
            this.barService.BarServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
